name: .NET Build and Pull Request Validation

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release --no-build

  validate_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Author
      id: check_author
      run: |
        author=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        allowed_users=("ngochung130201")  # Add allowed usernames here
        if [[ ! " ${allowed_users[@]} " =~ " $author " ]]; then
          echo "Unauthorized user. Only specific users are allowed to open pull requests."
          exit 1
        fi
